[tool.poetry]
name = "celery-ml"
version = "0.1.0"
description = ""
authors = ["Tanmaypatil123 <tanmay@modelslab.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
